Create a function to find executable using winreg
ansys/pyrocky pull request #148
Opened 2024-12-30 18:07 UTC by Adrian-B-Moreira

* Creates a function to find executable using winreg
* Updates the code to get the exe from winreg if Windows or ansys-tools-path if Linux (in order to keep Rocky standalone compatibility)
* Add doc to the functions

2024-12-30 18:10 UTC, Adrian-B-Moreira commented
@igortg  At first I thought about embedding the winreg code inside the find_executable, but the code would be very polluted, difficult to understand and would have many layers of indentation. So I kept them (`winreg` and `ansys-tools-path` approaches) separate.

2025-01-02 16:21 UTC, igortg requested changes

2025-01-02 16:21 UTC, igortg commented on src/ansys/rocky/core/launcher.py
> +    executable: Optional[Union[Path, str]] = None,
Why do you need `executable` here?

2025-01-02 16:21 UTC, igortg commented on src/ansys/rocky/core/launcher.py
> +    if sys.platform == "win32":
All this (218-227) should be encapsulated in a `_find_executable` function.

2025-01-02 20:55 UTC, igortg approved these changes

2025-01-02 20:55 UTC, igortg commented on src/ansys/rocky/core/launcher.py
> +    version: int,
```suggestion
    version: Optional[int],
```

2025-01-03 11:56 UTC, merged