Added use of GridFunctions to an example
ansys/pyrocky pull request #59
Opened 2024-05-20 13:59 UTC by fingeraugusto

ROCKY-21867

2024-05-20 14:00 UTC, fingeraugusto commented on examples/basic_examples/particle_wall_interaction_with_motion.py
> +# Obtain the maximum velocity the particles at each time step.
# Obtain the maximum and minimum velocities of the particles at each time step.

2024-05-20 14:00 UTC, fingeraugusto commented on examples/basic_examples/particle_wall_interaction_with_motion.py
> +velocity_times = study.GetTimeSet()
probably change to use particles instead of study

2024-05-21 12:42 UTC, alexandrelff approved these changes

2024-05-22 12:53 UTC, igortg requested changes
Can you add a screenshot of how the plot is being rendered with this change?

2024-05-22 12:53 UTC, igortg commented on examples/basic_examples/particle_wall_interaction_with_motion.py
> +velocity_times = study.GetTimeSet()
You can use the Study.

Just rename the variable to `simulation_times`, to give the reader the sense that this is not only related to the velocity.

2024-05-23 20:26 UTC, igortg approved these changes

2024-05-23 20:36 UTC, merged